text_file=open("first_group.txt", "wt")
text_file.write("Dasha, 82 балів\n")
text_file.write("Katya, 91 балів\n")
text_file.write("Petya, 66 балів\n")
text_file.write("Vera, 98 балів\n")
text_file.write("Sasha, 56 балів\n")
text_file.close()

text_file=open("second_group.txt", "wt")
text_file.write("Lera, 97 балів\n")
text_file.write("Ilona, 78 балів\n")
text_file.write("Nastya, 32 балів\n")
text_file.write("Ira, 42 балів\n")
text_file.write("Masha, 86 балів\n")
text_file.close()
